/*
 * generated by Xtext 2.38.0
 */
package fr.n7.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class PDL3GrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ProcessElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.PDL3.Process");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cProcessKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cWorkdefinitionsKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cColonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cWorkDefinitionsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cWorkDefinitionsIDTerminalRuleCall_5_0 = (RuleCall)cWorkDefinitionsAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cSemicolonKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cWorkDefinitionsAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cWorkDefinitionsIDTerminalRuleCall_6_1_0 = (RuleCall)cWorkDefinitionsAssignment_6_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cWorksequencesKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cColonKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cWorkSequencesAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cWorkSequencesWorkSequenceParserRuleCall_10_0 = (RuleCall)cWorkSequencesAssignment_10.eContents().get(0);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cSemicolonKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment cWorkSequencesAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final RuleCall cWorkSequencesWorkSequenceParserRuleCall_11_1_0 = (RuleCall)cWorkSequencesAssignment_11_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//Process:
		//  'process' ':' name=ID
		//  'workdefinitions' ':' workDefinitions+=ID ( ';' workDefinitions+=ID )* ';'
		//  'worksequences' ':' workSequences+=WorkSequence ( ';' workSequences+=WorkSequence )* ';'?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'process' ':' name=ID
		//'workdefinitions' ':' workDefinitions+=ID ( ';' workDefinitions+=ID )* ';'
		//'worksequences' ':' workSequences+=WorkSequence ( ';' workSequences+=WorkSequence )* ';'?
		public Group getGroup() { return cGroup; }
		
		//'process'
		public Keyword getProcessKeyword_0() { return cProcessKeyword_0; }
		
		//':'
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }
		
		//'workdefinitions'
		public Keyword getWorkdefinitionsKeyword_3() { return cWorkdefinitionsKeyword_3; }
		
		//':'
		public Keyword getColonKeyword_4() { return cColonKeyword_4; }
		
		//workDefinitions+=ID
		public Assignment getWorkDefinitionsAssignment_5() { return cWorkDefinitionsAssignment_5; }
		
		//ID
		public RuleCall getWorkDefinitionsIDTerminalRuleCall_5_0() { return cWorkDefinitionsIDTerminalRuleCall_5_0; }
		
		//( ';' workDefinitions+=ID )*
		public Group getGroup_6() { return cGroup_6; }
		
		//';'
		public Keyword getSemicolonKeyword_6_0() { return cSemicolonKeyword_6_0; }
		
		//workDefinitions+=ID
		public Assignment getWorkDefinitionsAssignment_6_1() { return cWorkDefinitionsAssignment_6_1; }
		
		//ID
		public RuleCall getWorkDefinitionsIDTerminalRuleCall_6_1_0() { return cWorkDefinitionsIDTerminalRuleCall_6_1_0; }
		
		//';'
		public Keyword getSemicolonKeyword_7() { return cSemicolonKeyword_7; }
		
		//'worksequences'
		public Keyword getWorksequencesKeyword_8() { return cWorksequencesKeyword_8; }
		
		//':'
		public Keyword getColonKeyword_9() { return cColonKeyword_9; }
		
		//workSequences+=WorkSequence
		public Assignment getWorkSequencesAssignment_10() { return cWorkSequencesAssignment_10; }
		
		//WorkSequence
		public RuleCall getWorkSequencesWorkSequenceParserRuleCall_10_0() { return cWorkSequencesWorkSequenceParserRuleCall_10_0; }
		
		//( ';' workSequences+=WorkSequence )*
		public Group getGroup_11() { return cGroup_11; }
		
		//';'
		public Keyword getSemicolonKeyword_11_0() { return cSemicolonKeyword_11_0; }
		
		//workSequences+=WorkSequence
		public Assignment getWorkSequencesAssignment_11_1() { return cWorkSequencesAssignment_11_1; }
		
		//WorkSequence
		public RuleCall getWorkSequencesWorkSequenceParserRuleCall_11_1_0() { return cWorkSequencesWorkSequenceParserRuleCall_11_1_0; }
		
		//';'?
		public Keyword getSemicolonKeyword_12() { return cSemicolonKeyword_12; }
	}
	public class WorkSequenceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.PDL3.WorkSequence");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cPredecessorAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cPredecessorWorkDefinitionCrossReference_0_0 = (CrossReference)cPredecessorAssignment_0.eContents().get(0);
		private final RuleCall cPredecessorWorkDefinitionIDTerminalRuleCall_0_0_1 = (RuleCall)cPredecessorWorkDefinitionCrossReference_0_0.eContents().get(1);
		private final Assignment cLinkTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cLinkTypeWorkSequenceTypeEnumRuleCall_1_0 = (RuleCall)cLinkTypeAssignment_1.eContents().get(0);
		private final Assignment cSuccessorAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cSuccessorWorkDefinitionCrossReference_2_0 = (CrossReference)cSuccessorAssignment_2.eContents().get(0);
		private final RuleCall cSuccessorWorkDefinitionIDTerminalRuleCall_2_0_1 = (RuleCall)cSuccessorWorkDefinitionCrossReference_2_0.eContents().get(1);
		
		//WorkSequence:
		//  predecessor=[WorkDefinition] linkType=WorkSequenceType successor=[WorkDefinition]
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//predecessor=[WorkDefinition] linkType=WorkSequenceType successor=[WorkDefinition]
		public Group getGroup() { return cGroup; }
		
		//predecessor=[WorkDefinition]
		public Assignment getPredecessorAssignment_0() { return cPredecessorAssignment_0; }
		
		//[WorkDefinition]
		public CrossReference getPredecessorWorkDefinitionCrossReference_0_0() { return cPredecessorWorkDefinitionCrossReference_0_0; }
		
		//ID
		public RuleCall getPredecessorWorkDefinitionIDTerminalRuleCall_0_0_1() { return cPredecessorWorkDefinitionIDTerminalRuleCall_0_0_1; }
		
		//linkType=WorkSequenceType
		public Assignment getLinkTypeAssignment_1() { return cLinkTypeAssignment_1; }
		
		//WorkSequenceType
		public RuleCall getLinkTypeWorkSequenceTypeEnumRuleCall_1_0() { return cLinkTypeWorkSequenceTypeEnumRuleCall_1_0; }
		
		//successor=[WorkDefinition]
		public Assignment getSuccessorAssignment_2() { return cSuccessorAssignment_2; }
		
		//[WorkDefinition]
		public CrossReference getSuccessorWorkDefinitionCrossReference_2_0() { return cSuccessorWorkDefinitionCrossReference_2_0; }
		
		//ID
		public RuleCall getSuccessorWorkDefinitionIDTerminalRuleCall_2_0_1() { return cSuccessorWorkDefinitionIDTerminalRuleCall_2_0_1; }
	}
	public class WorkDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.PDL3.WorkDefinition");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//// Ce bloc définit WorkDefinition comme un simple identifiant (déduit automatiquement)
		//WorkDefinition:
		//  name=ID
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID
		public Assignment getNameAssignment() { return cNameAssignment; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0() { return cNameIDTerminalRuleCall_0; }
	}
	
	public class WorkSequenceTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.PDL3.WorkSequenceType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cS2sEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cS2sS2sKeyword_0_0 = (Keyword)cS2sEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cF2sEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cF2sF2sKeyword_1_0 = (Keyword)cF2sEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cS2fEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cS2fS2fKeyword_2_0 = (Keyword)cS2fEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cF2fEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cF2fF2fKeyword_3_0 = (Keyword)cF2fEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum WorkSequenceType:
		//  s2s | f2s | s2f | f2f
		//;
		public EnumRule getRule() { return rule; }
		
		//s2s | f2s | s2f | f2f
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//s2s
		public EnumLiteralDeclaration getS2sEnumLiteralDeclaration_0() { return cS2sEnumLiteralDeclaration_0; }
		
		public Keyword getS2sS2sKeyword_0_0() { return cS2sS2sKeyword_0_0; }
		
		//f2s
		public EnumLiteralDeclaration getF2sEnumLiteralDeclaration_1() { return cF2sEnumLiteralDeclaration_1; }
		
		public Keyword getF2sF2sKeyword_1_0() { return cF2sF2sKeyword_1_0; }
		
		//s2f
		public EnumLiteralDeclaration getS2fEnumLiteralDeclaration_2() { return cS2fEnumLiteralDeclaration_2; }
		
		public Keyword getS2fS2fKeyword_2_0() { return cS2fS2fKeyword_2_0; }
		
		//f2f
		public EnumLiteralDeclaration getF2fEnumLiteralDeclaration_3() { return cF2fEnumLiteralDeclaration_3; }
		
		public Keyword getF2fF2fKeyword_3_0() { return cF2fF2fKeyword_3_0; }
	}
	
	private final ProcessElements pProcess;
	private final WorkSequenceElements pWorkSequence;
	private final WorkSequenceTypeElements eWorkSequenceType;
	private final WorkDefinitionElements pWorkDefinition;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public PDL3GrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pProcess = new ProcessElements();
		this.pWorkSequence = new WorkSequenceElements();
		this.eWorkSequenceType = new WorkSequenceTypeElements();
		this.pWorkDefinition = new WorkDefinitionElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("fr.n7.PDL3".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Process:
	//  'process' ':' name=ID
	//  'workdefinitions' ':' workDefinitions+=ID ( ';' workDefinitions+=ID )* ';'
	//  'worksequences' ':' workSequences+=WorkSequence ( ';' workSequences+=WorkSequence )* ';'?
	//;
	public ProcessElements getProcessAccess() {
		return pProcess;
	}
	
	public ParserRule getProcessRule() {
		return getProcessAccess().getRule();
	}
	
	//WorkSequence:
	//  predecessor=[WorkDefinition] linkType=WorkSequenceType successor=[WorkDefinition]
	//;
	public WorkSequenceElements getWorkSequenceAccess() {
		return pWorkSequence;
	}
	
	public ParserRule getWorkSequenceRule() {
		return getWorkSequenceAccess().getRule();
	}
	
	//enum WorkSequenceType:
	//  s2s | f2s | s2f | f2f
	//;
	public WorkSequenceTypeElements getWorkSequenceTypeAccess() {
		return eWorkSequenceType;
	}
	
	public EnumRule getWorkSequenceTypeRule() {
		return getWorkSequenceTypeAccess().getRule();
	}
	
	//// Ce bloc définit WorkDefinition comme un simple identifiant (déduit automatiquement)
	//WorkDefinition:
	//  name=ID
	//;
	public WorkDefinitionElements getWorkDefinitionAccess() {
		return pWorkDefinition;
	}
	
	public ParserRule getWorkDefinitionRule() {
		return getWorkDefinitionAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
