/**
 * generated by Xtext 2.38.0
 */
package fr.n7.pDL1;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Allocation Ressource</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.pDL1.AllocationRessource#getResource <em>Resource</em>}</li>
 *   <li>{@link fr.n7.pDL1.AllocationRessource#getNbRessource <em>Nb Ressource</em>}</li>
 * </ul>
 *
 * @see fr.n7.pDL1.PDL1Package#getAllocationRessource()
 * @model
 * @generated
 */
public interface AllocationRessource extends EObject
{
  /**
   * Returns the value of the '<em><b>Resource</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Resource</em>' reference.
   * @see #setResource(Ressource)
   * @see fr.n7.pDL1.PDL1Package#getAllocationRessource_Resource()
   * @model
   * @generated
   */
  Ressource getResource();

  /**
   * Sets the value of the '{@link fr.n7.pDL1.AllocationRessource#getResource <em>Resource</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Resource</em>' reference.
   * @see #getResource()
   * @generated
   */
  void setResource(Ressource value);

  /**
   * Returns the value of the '<em><b>Nb Ressource</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nb Ressource</em>' attribute.
   * @see #setNbRessource(int)
   * @see fr.n7.pDL1.PDL1Package#getAllocationRessource_NbRessource()
   * @model
   * @generated
   */
  int getNbRessource();

  /**
   * Sets the value of the '{@link fr.n7.pDL1.AllocationRessource#getNbRessource <em>Nb Ressource</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nb Ressource</em>' attribute.
   * @see #getNbRessource()
   * @generated
   */
  void setNbRessource(int value);

} // AllocationRessource
