/**
 * generated by Xtext 2.38.0
 */
package fr.n7.pDL3;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Work Sequence Type</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see fr.n7.pDL3.PDL3Package#getWorkSequenceType()
 * @model
 * @generated
 */
public enum WorkSequenceType implements Enumerator
{
  /**
   * The '<em><b>S2s</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #S2S_VALUE
   * @generated
   * @ordered
   */
  S2S(0, "s2s", "s2s"),

  /**
   * The '<em><b>F2s</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #F2S_VALUE
   * @generated
   * @ordered
   */
  F2S(1, "f2s", "f2s"),

  /**
   * The '<em><b>S2f</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #S2F_VALUE
   * @generated
   * @ordered
   */
  S2F(2, "s2f", "s2f"),

  /**
   * The '<em><b>F2f</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #F2F_VALUE
   * @generated
   * @ordered
   */
  F2F(3, "f2f", "f2f");

  /**
   * The '<em><b>S2s</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #S2S
   * @model name="s2s"
   * @generated
   * @ordered
   */
  public static final int S2S_VALUE = 0;

  /**
   * The '<em><b>F2s</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #F2S
   * @model name="f2s"
   * @generated
   * @ordered
   */
  public static final int F2S_VALUE = 1;

  /**
   * The '<em><b>S2f</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #S2F
   * @model name="s2f"
   * @generated
   * @ordered
   */
  public static final int S2F_VALUE = 2;

  /**
   * The '<em><b>F2f</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #F2F
   * @model name="f2f"
   * @generated
   * @ordered
   */
  public static final int F2F_VALUE = 3;

  /**
   * An array of all the '<em><b>Work Sequence Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final WorkSequenceType[] VALUES_ARRAY =
    new WorkSequenceType[]
    {
      S2S,
      F2S,
      S2F,
      F2F,
    };

  /**
   * A public read-only list of all the '<em><b>Work Sequence Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<WorkSequenceType> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Work Sequence Type</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static WorkSequenceType get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      WorkSequenceType result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Work Sequence Type</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static WorkSequenceType getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      WorkSequenceType result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Work Sequence Type</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static WorkSequenceType get(int value)
  {
    switch (value)
    {
      case S2S_VALUE: return S2S;
      case F2S_VALUE: return F2S;
      case S2F_VALUE: return S2F;
      case F2F_VALUE: return F2F;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private WorkSequenceType(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //WorkSequenceType
