/**
 * generated by Xtext 2.38.0
 */
package fr.n7.pDL1.impl;

import fr.n7.pDL1.AllocationRessource;
import fr.n7.pDL1.PDL1Package;
import fr.n7.pDL1.Ressource;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Allocation Ressource</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.pDL1.impl.AllocationRessourceImpl#getResource <em>Resource</em>}</li>
 *   <li>{@link fr.n7.pDL1.impl.AllocationRessourceImpl#getNbRessource <em>Nb Ressource</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AllocationRessourceImpl extends MinimalEObjectImpl.Container implements AllocationRessource
{
  /**
   * The cached value of the '{@link #getResource() <em>Resource</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getResource()
   * @generated
   * @ordered
   */
  protected Ressource resource;

  /**
   * The default value of the '{@link #getNbRessource() <em>Nb Ressource</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNbRessource()
   * @generated
   * @ordered
   */
  protected static final int NB_RESSOURCE_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getNbRessource() <em>Nb Ressource</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNbRessource()
   * @generated
   * @ordered
   */
  protected int nbRessource = NB_RESSOURCE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AllocationRessourceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PDL1Package.Literals.ALLOCATION_RESSOURCE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Ressource getResource()
  {
    if (resource != null && resource.eIsProxy())
    {
      InternalEObject oldResource = (InternalEObject)resource;
      resource = (Ressource)eResolveProxy(oldResource);
      if (resource != oldResource)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, PDL1Package.ALLOCATION_RESSOURCE__RESOURCE, oldResource, resource));
      }
    }
    return resource;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Ressource basicGetResource()
  {
    return resource;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setResource(Ressource newResource)
  {
    Ressource oldResource = resource;
    resource = newResource;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PDL1Package.ALLOCATION_RESSOURCE__RESOURCE, oldResource, resource));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getNbRessource()
  {
    return nbRessource;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNbRessource(int newNbRessource)
  {
    int oldNbRessource = nbRessource;
    nbRessource = newNbRessource;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PDL1Package.ALLOCATION_RESSOURCE__NB_RESSOURCE, oldNbRessource, nbRessource));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PDL1Package.ALLOCATION_RESSOURCE__RESOURCE:
        if (resolve) return getResource();
        return basicGetResource();
      case PDL1Package.ALLOCATION_RESSOURCE__NB_RESSOURCE:
        return getNbRessource();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PDL1Package.ALLOCATION_RESSOURCE__RESOURCE:
        setResource((Ressource)newValue);
        return;
      case PDL1Package.ALLOCATION_RESSOURCE__NB_RESSOURCE:
        setNbRessource((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PDL1Package.ALLOCATION_RESSOURCE__RESOURCE:
        setResource((Ressource)null);
        return;
      case PDL1Package.ALLOCATION_RESSOURCE__NB_RESSOURCE:
        setNbRessource(NB_RESSOURCE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PDL1Package.ALLOCATION_RESSOURCE__RESOURCE:
        return resource != null;
      case PDL1Package.ALLOCATION_RESSOURCE__NB_RESSOURCE:
        return nbRessource != NB_RESSOURCE_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (nbRessource: ");
    result.append(nbRessource);
    result.append(')');
    return result.toString();
  }

} //AllocationRessourceImpl
